### ISSUE TITLE
Problem processing complex type

### ISSUE THREAD

**Issue by JakubPetriska** [sevenclev/node-soap-graphql#2]
Hello, first of all thanks for this library. I really appreciate your work and the fact that you're making it public.

I tried creating GraphQL types from WSDL schema and when the generator hits this type:
```xml
<xs:element name="customTemplateData">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="key" minOccurs="0" type="xs:string"/>
            <xs:element name="value" minOccurs="0" type="xs:anyType"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
```

I get the following exception:
```
Error: could not resolve output type for { name: 'customTemplateData', type: undefined, isList: false }
    at GraphqlOutputFieldResolver.resolve (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:207:32)
    at /home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:266:28
    at Array.forEach (<anonymous>)
    at GraphqlOutputFieldResolver.appendObjectTypeFields (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:264:25)
    at fields (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:246:18)
    at resolveThunk (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/definition.js:438:40)
    at defineFieldMap (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/definition.js:625:18)
    at GraphQLObjectType.getFields (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/definition.js:579:27)
    at typeMapReducer (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/schema.js:280:78)
    at typeMapReducer (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/schema.js:145:28)
    at Object.<anonymous> (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap-graphql.ts:67:12)
    at step (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/dist/src/soap-graphql.js:32:23)
    at Object.next (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/dist/src/soap-graphql.js:13:53)
    at fulfilled (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/dist/src/soap-graphql.js:4:58)
Caused by: Error: Must provide name.
    at devAssert (/home/jakub/Projects/silverdat-boost/node_modules/graphql/jsutils/devAssert.js:12:11)
    at new GraphQLObjectType (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/definition.js:571:63)
    at GraphqlOutputFieldResolver.createObjectType (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:239:16)
    at GraphqlOutputFieldResolver.resolveOutputType (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:226:56)
    at GraphqlOutputFieldResolver.resolve (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:204:50)
    at /home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:266:28
    at Array.forEach (<anonymous>)
    at GraphqlOutputFieldResolver.appendObjectTypeFields (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:264:25)
    at fields (/home/jakub/Projects/silverdat-boost/node_modules/soap-graphql/src/soap2graphql/schema-resolver.ts:246:18)
    at resolveThunk (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/definition.js:438:40)
    at defineFieldMap (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/definition.js:625:18)
    at GraphQLObjectType.getFields (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/definition.js:579:27)
    at typeMapReducer (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/schema.js:280:78)
    at typeMapReducer (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/home/jakub/Projects/silverdat-boost/node_modules/graphql/type/schema.js:145:28)
```

Is it possible that the library is not capable of processing the mentioned type? If there's anything that I should submit to make resolving this issue easier, please just let me know.

**Comment by Yogu** [comment]
We are experiencing the same problem with this complex type

{code}
<xs:complexType name="getDocumentCategoriesResponseDTO">
    <xs:complexContent>
        <xs:extension base="tns:abstractResponseDTO">
            <xs:sequence>
                <xs:element name="categories" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="category" type="tns:lisExpMODocumentCategoryDTO" minOccurs="0"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
{code}

@JakubPetriska did you by any chance find a way around this?

**Comment by sevenclev** [comment]
https://www.npmjs.com/package/soap-graphql/v/1.1.0-fix.anonymous.complex.types.1
